### ISSUE TITLE
OSC 1.8.15 Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/ardour-control#10]
Hi,
After upgrade to Open Stage Control 1.8.15 and the last version of ardour-control, i get this error :
```
(ERROR, CLIENT) Uncaught TypeError: Cannot read property 'type' of undefined
    at parse (src/client/parser.js:46:42)
    at load (src/client/managers/session/index.js:47:23)
```
No problems with older version of ardour-control.
Thank you for the software !

**Comment by jean-emmanuel** [comment]
I'm not having no issue with the latest o-s-c version (v1.14.5) and a fresh ardour-control clone, are you confident you're using the same ?

**Comment by wargreen** [comment]
Ok, i've downloaded the last version (1.14.5) yesterday but not installed... To many multitasking for my brain.
Sorry for the noise...!
