### ISSUE TITLE
Bug: track plugin view

### ISSUE THREAD

**Issue by manfred-mp** [jean-emmanuel/ardour-control#5]
Track plugin view is broken due to 'stretch=true' in elements. Don't know if default is true in OSC side which is causing this or something in this custom control.

**Comment by jean-emmanuel** [comment]
Just in case I have updated the session with the latest code from open-stage-control/examples.
What's broken exactly ?

**Comment by manfred-mp** [comment]
![plugin_nok](https://user-images.githubusercontent.com/1030705/48509410-bae36c00-e859-11e8-99a8-d504d2ca1210.jpg)
![plugin_ok](https://user-images.githubusercontent.com/1030705/48509416-bdde5c80-e859-11e8-9f7f-cad75592d7f8.jpg)

[ardour-plugins-module.js.txt](https://github.com/jean-emmanuel/ardour-control/files/2582469/ardour-plugins-module.js.txt)

Easier with pics. Also attached modified module file for reference.
