### ISSUE TITLE
Feedback from Ardour

### ISSUE THREAD

**Issue by Psirus** [jean-emmanuel/ardour-control#6]
First off, thank you very much for your work. It's a really nice piece of software.

Now, I'm using openstagecontrol 0.49.12 and Ardour 5.12. I'm starting it like this:
~~~
open-stage-control -s 127.0.0.1:3819 --port 7777 -l ardour.json -c ardour-plugins-module.js
~~~
My Ardour OSC settings look like this:
![Bildschirmfoto von 2020-04-04 10-33-37](https://user-images.githubusercontent.com/1187292/78422705-85633c80-7661-11ea-92db-bf678b857490.png)
![Bildschirmfoto von 2020-04-04 10-33-55](https://user-images.githubusercontent.com/1187292/78422706-86946980-7661-11ea-89f8-edbeab665194.png)

Controlling Ardour works fine, however the feedback from Ardour is flaky. E.g. the Master meter and the meter in the "Track" tab show their current values, but the strips in the "Mixer" tab don't. When switching tracks, sometimes the name gets synced to the OSC surface, sometimes it isn't. Loading plugins in the "Track" tab also doesn't work.

How do I set this up correctly?

Btw, what are the SEL² buttons for?

**Comment by jean-emmanuel** [comment]
Hi, have you pressed the "connect" button in the first tab ? it ensures ardour only sends the feedback that's needed and defines the bank size (this controller only works with a limited bank size). Ardour sends **a lot** of feedback and eventually it may lead to packet losses, so you might wanna check this out too : https://github.com/jean-emmanuel/ardour-control#troubleshooting

> Btw, what are the SEL² buttons for?

If I remember correctly I used it as an alternate select button that allows keeping the previously selected track (with the regular "sel" button) in memory.

I'm not maintaining this project anymore but I'll probably build a new one for Ardour 6 using Open Stage Control v1 at some point.

**Comment by Psirus** [comment]
Thank you, pressing connect did indeed solve the problem.
