### ISSUE TITLE
Some irritations

### ISSUE THREAD

**Issue by Knollewurz** [jean-emmanuel/ardour-control#8]
Ahoi,
nice work but there are some things twisted here :-)
tryed to start it like:
open-stage-control -- -l mypath/to/ardour.js -c mypath/to/ardour-plugins-module.js -s 127.0.0.1:3819
but first target is named ardour.json!  Typo?
when giving correct path, I get: "[Renderer process error]
Uncaught Error: Malformed session file." in bash

using the example from the .deb (/usr/lib/open-stage-control/resources/app/examples/ardour.json ) I got it working (kind of)

and it looks like you forgot the cat in troubleshooting (readme.md)
# check buffer size
[cat]/proc/sys/net/core/rmem_default

hope this is any use
knollewurz

**Comment by jean-emmanuel** [comment]
Thanks, typos are fixed now. Regarding the error I think you're using the wrong version of OSC, the master branch is for OSC v1 / Ardour v6.

**Comment by Knollewurz** [comment]
Thank you! yes i havent found a .deb package for latest version yet :-) since i have a close deadline for the video I am workin on, I`ll try to figure it out later :-)

keep on rockin`and stay healthy

**Comment by jean-emmanuel** [comment]
Here it is : https://github.com/jean-emmanuel/open-stage-control/releases/tag/v1.0.0-beta7
good luck with your project
