### ISSUE TITLE
Live version

### ISSUE THREAD

**Issue by wargreen** [jean-emmanuel/ardour-control#9]
Hi,
I've make a version optimised for a live usage (with big faders, mute alway shown, loop state...). Do you interested to make a branch with it ?

**Comment by jean-emmanuel** [comment]
Maybe I can integrate your changes as options, would you mind uploading the session file here ?

**Comment by wargreen** [comment]
Sure !
(Github don't support .json, so i've rename it...)
[ardour.log](https://github.com/jean-emmanuel/ardour-control/files/5142780/ardour.log)

It's intended to be used with Plugins and Gain Input.
Change log :

- Transport section, Loop, prev/next marker, double tap to record
- Mute outside of the record block, size in % with max height
- Double tap to master mute
- Big compact faders
- Plugins container in % with bigger scrollbar
- Maybe somthing i've forgot...

Thank you for the work, i use it for FOH on our new street theater show !
